
name:  run masjid el houda

on:
  push:
    branches:
      - master

    jobs:
      test:
        runs-on: macos-latest
        steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-java@v3
           with:
            java-version: "11"
            distribution: "temurin"
            cache: maven
         - run: mvn test
