name: Run Massjid El Houda

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: action/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - run: mvn test